### ISSUE TITLE
setup

### ISSUE THREAD

**Issue by jerryowusu** [jerryowusu/math-magicians#2]
please check in the dev branch for the setup. I tried submitting that link but it is not being accepted in the request link. 
Here is a link to the setup dev branch.

[Click to Setup](https://github.com/jerryowusu/math-magicians)

**Comment by Mihndim2020** [comment]
# STATUS: INVALID!!!  :x: :x: :x: 

Hi @jerryowusu,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code, please make sure your implement the following changes before you resubmit for review. 

## Required Changes ♻️
_Check the comments below._
- [x] Please kindly raise a [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request), from a feature branch to the dev branch before resubmitting for review since you are to follow `[Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md)` for this particular project. The link is not being accepted because you have not raised a `PR`. Kindly raise a `pull request` and submit the `pull request` link. 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by jerryowusu** [comment]
Thanks
